name: ridersapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  google_fonts: ^5.1.0
  flutter_onboarding_slider: ^1.0.11
  provider: ^6.1.2
  image_picker: ^0.8.4+8
  path_provider: ^2.0.11
  shared_preferences: ^2.0.9
  pinput: ^2.2.17
  fluttertoast: ^8.2.6
  google_maps_flutter: ^2.5.0
  flutter_font_picker: ^1.4.0
  intl: ^0.18.1
  url_launcher: ^6.0.9
  flutter_contacts: ^1.1.9+2
  #location: ^4.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/contacts.json
